//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentPerformanceInfo
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Rank { get; set; }
        public string TimeUtilization { get; set; }
        public string EstWorkingTime { get; set; }
        public string TotalLPH { get; set; }
        public string TotalLeads { get; set; }
        public string TotalNoXFER { get; set; }
        public string TotalProjectedLead { get; set; }
        public string Date { get; set; }
    }
}
