//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class choice_map
    {
        public int id { get; set; }
        public string url { get; set; }
        public string web_variable { get; set; }
        public string web_choice { get; set; }
        public string our_choice { get; set; }
    }
}
