//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyEmailReport
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Sent { get; set; }
        public string ReportName { get; set; }
        public string Time { get; set; }
        public string Path { get; set; }
    }
}
