//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degree_Of_Interest
    {
        public int doi_id { get; set; }
        public string doi_degree { get; set; }
        public Nullable<int> doi_rank { get; set; }
    }
}
