//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdSoup
    {
        public int EdSoupID { get; set; }
        public string Campaign { get; set; }
        public string CampaignGroup { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string ANI { get; set; }
        public Nullable<System.DateTime> Duration { get; set; }
        public string Disposition { get; set; }
        public string Agent { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
