//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdSoupProfileLead
    {
        public int EDSoupProfileLeadID { get; set; }
        public string Campaign { get; set; }
        public string CampaignGroup { get; set; }
        public string StudentID { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Leads { get; set; }
    }
}
