//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorReport
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string ErrorDescription { get; set; }
        public byte[] ErrorScreenshot { get; set; }
        public string Steps { get; set; }
        public string Remarks { get; set; }
        public string AgentInfo { get; set; }
        public string ClientInfo { get; set; }
        public byte[] ClientInfoScreenshot { get; set; }
        public string MSUrl { get; set; }
        public byte[] MSScreenshot { get; set; }
        public string CCUrl { get; set; }
        public byte[] CCScreenshot { get; set; }
        public string HEGUrl { get; set; }
        public byte[] HEGScreenshot { get; set; }
        public string Status { get; set; }
        public string Resolution { get; set; }
    }
}
