//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsubMappingValue
    {
        public int EsubMappingId { get; set; }
        public string CCMappingValue { get; set; }
        public string MSEMappingValue { get; set; }
        public string MCM1MappingValue { get; set; }
        public string MCM2MappingValue { get; set; }
        public string MCM3MappingValue { get; set; }
        public string MSEMajorMappingValue { get; set; }
        public int Id { get; set; }
    
        public virtual EsubMapping EsubMapping { get; set; }
    }
}
