//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSO_DATA
    {
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string primary_phone { get; set; }
        public string field_of_interest { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> added { get; set; }
        public string zip { get; set; }
        public string submitted_data { get; set; }
        public string submitted_site { get; set; }
        public string result { get; set; }
    }
}
