//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class gvd_data_back_12_5_2015
    {
        public Nullable<int> CONTACT_ID { get; set; }
        public string CONTACT_RECORD_CREATE_TIMESTAMP { get; set; }
        public string CONTACT_RECORD_MODIFIED_TIMESTAMP { get; set; }
        public Nullable<short> CONTACT_IN_DNC { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public Nullable<long> number1 { get; set; }
        public string number2 { get; set; }
        public string number3 { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string company { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string email { get; set; }
        public Nullable<int> leadid { get; set; }
        public string domain { get; set; }
        public string highest_edu_level { get; set; }
        public string program_of_interest { get; set; }
        public string grad_year { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string dreamjob { get; set; }
        public string reg_ip { get; set; }
        public string posteddisposition { get; set; }
        public string postednotes { get; set; }
        public string apt { get; set; }
        public string LastCampaign { get; set; }
        public Nullable<System.DateTime> submitted_date { get; set; }
        public string submitted_data { get; set; }
        public string post_function { get; set; }
        public string post_result { get; set; }
        public string query_string { get; set; }
        public string result { get; set; }
        public string submitted_site { get; set; }
        public Nullable<bool> isDupe { get; set; }
        public Nullable<bool> first_pass { get; set; }
        public string sub_id { get; set; }
        public Nullable<bool> show_result { get; set; }
        public string optindate { get; set; }
        public string optintime { get; set; }
        public string vendor_id { get; set; }
        public int id { get; set; }
    }
}
