//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class gvd_routing
    {
        public int id { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public string sub_id { get; set; }
        public string send_to { get; set; }
        public string fail_to { get; set; }
        public string prefix { get; set; }
        public string second_fail { get; set; }
        public Nullable<double> daily_cap { get; set; }
        public string daily_roll_to { get; set; }
        public Nullable<bool> post_email { get; set; }
    }
}
