//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEG
    {
        public int HEGID { get; set; }
        public string Campaign { get; set; }
        public string CampaignGroup { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string School { get; set; }
        public string LeadId { get; set; }
        public string Phone { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateProvince { get; set; }
        public string PostalCode { get; set; }
        public string Email { get; set; }
        public string VisitorIPAddress { get; set; }
        public string CCListId { get; set; }
        public string CCSubId { get; set; }
        public string CCRepId { get; set; }
        public string CCIPAddress { get; set; }
        public string DeliveryStatus { get; set; }
        public string ReturnReason { get; set; }
        public string FilteredReason { get; set; }
    }
}
