//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportHistory
    {
        public int ImportHistoryID { get; set; }
        public string StoredProcedure { get; set; }
        public string FileName { get; set; }
        public string Status { get; set; }
        public Nullable<int> RowCount { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
    }
}
