//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Map
    {
        public int map_id { get; set; }
        public string map_school { get; set; }
        public string map_AOI { get; set; }
        public string map_education { get; set; }
        public string map_school_type { get; set; }
        public string map_citizen { get; set; }
        public string map_degree { get; set; }
        public string map_state { get; set; }
        public string map_military { get; set; }
    }
}
