//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaSpike
    {
        public int MediaSpikeID { get; set; }
        public string Campaign { get; set; }
        public string CampaignGroup { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string SourceID { get; set; }
        public string RepID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string SubmissionID { get; set; }
        public string SchoolCode { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public string Conversion { get; set; }
        public string Submissions { get; set; }
        public string Valid { get; set; }
        public string Invalid { get; set; }
        public string Timestamp { get; set; }
        public string CallReceived { get; set; }
        public string CallValid { get; set; }
        public string Transfer { get; set; }
    }
}
