//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class mfp_record
    {
        public int id { get; set; }
        public string AreaOfInterest { get; set; }
        public string Citizenship { get; set; }
        public string EducationLevel { get; set; }
        public string Age { get; set; }
        public string DegreeStartTimeframe { get; set; }
        public string Zip { get; set; }
        public Nullable<System.DateTime> date_submitted { get; set; }
        public string IP { get; set; }
        public string SubmittedData { get; set; }
        public string Result { get; set; }
    }
}
