//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class myfootpathaffiliate
    {
        public int mfp_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string primary_phone { get; set; }
        public string citizen { get; set; }
        public string field_of_interest { get; set; }
        public string has_hs_or_ged { get; set; }
        public string sub_id { get; set; }
        public string submitted_data { get; set; }
        public string submitted_site { get; set; }
        public string result { get; set; }
        public Nullable<System.DateTime> submitted_date { get; set; }
        public string vendor_id { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string optindate { get; set; }
        public string optintime { get; set; }
        public string ipaddress { get; set; }
        public Nullable<bool> show_result { get; set; }
        public string post_result { get; set; }
        public Nullable<bool> isDupe { get; set; }
        public Nullable<bool> first_pass { get; set; }
        public string lead_id { get; set; }
        public string post_function { get; set; }
        public string URL { get; set; }
        public string submitted_site2 { get; set; }
        public string query_string { get; set; }
        public Nullable<bool> force_reject { get; set; }
        public Nullable<System.DateTime> LastCallDate { get; set; }
        public Nullable<int> CallCount { get; set; }
        public string LastDisposition { get; set; }
        public Nullable<System.DateTime> LastSellDate { get; set; }
        public Nullable<int> SellCount { get; set; }
        public Nullable<int> LastUserID { get; set; }
        public string Recording { get; set; }
    }
}
