//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_info
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Zip { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string IP { get; set; }
        public string Citizen { get; set; }
        public string Graduated { get; set; }
        public string Interest { get; set; }
        public string LeadID { get; set; }
        public string OptInDate { get; set; }
        public string OptInTime { get; set; }
        public string SourceID { get; set; }
        public string post_URL { get; set; }
        public string fixed_string { get; set; }
        public string post_name { get; set; }
        public Nullable<bool> active { get; set; }
        public string URL { get; set; }
        public string notes { get; set; }
        public string rejected { get; set; }
        public string today { get; set; }
        public string method { get; set; }
        public Nullable<bool> reject { get; set; }
        public Nullable<double> reject_rate { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<double> revenue { get; set; }
    }
}
