//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuinStreet
    {
        public int QuinStreetID { get; set; }
        public string Campaign { get; set; }
        public string CampaignGroup { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string Arid { get; set; }
        public string Publisher { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<double> DatacaptureKey { get; set; }
        public Nullable<double> DatacaptureStatus { get; set; }
        public string CodeName { get; set; }
        public string DegreeOfInterest { get; set; }
        public string Program { get; set; }
        public string School { get; set; }
        public string EducationLevel { get; set; }
        public string HighSchoolGradYear { get; set; }
        public string DegreeStartTimeframe { get; set; }
        public string Areaofinterest { get; set; }
        public string EduPogramOfInterest { get; set; }
        public string RepresentativeId2 { get; set; }
        public string RemnantLeads { get; set; }
        public Nullable<double> DeVryLeads { get; set; }
    }
}
