//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_Detail
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string PrimaryPhone { get; set; }
        public int CompanyNameId { get; set; }
        public string SchoolName { get; set; }
        public int SchoolStatusId { get; set; }
        public Nullable<int> SubmitId { get; set; }
    }
}
