//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_OverrideInputs
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string ClientTelephone { get; set; }
        public bool OverrideInputOtherSchool { get; set; }
        public bool OverrideInputMSE { get; set; }
    }
}
