//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schools_Submitteds
    {
        public int Id { get; set; }
        public int SubmitId { get; set; }
        public Nullable<int> MSSchoolFoundQty { get; set; }
        public string MSSchoolFounds { get; set; }
        public Nullable<int> CCSchoolFoundQty { get; set; }
        public string CCSchoolFounds { get; set; }
        public Nullable<int> HEGSchoolFoundsQty { get; set; }
        public string HEGSchoolFounds { get; set; }
        public Nullable<int> MSSubmittedQty { get; set; }
        public string MSSubmitteds { get; set; }
        public Nullable<int> CCSubmittedQty { get; set; }
        public string CCSubmitteds { get; set; }
        public Nullable<int> HEGSubmittedQty { get; set; }
        public string HEGSubmitteds { get; set; }
        public string EDSoupSubmitted { get; set; }
        public string AllSchools { get; set; }
        public Nullable<int> TotalSubmitted { get; set; }
        public string KeyPathSubmitted { get; set; }
        public string KeyPath2Submitted { get; set; }
        public Nullable<int> MSESchoolFoundQty { get; set; }
        public string MSESchoolFounds { get; set; }
        public Nullable<int> MSESubmittedQty { get; set; }
        public string MSESubmitteds { get; set; }
        public Nullable<int> HEGCSchoolFoundsQty { get; set; }
        public string HEGCSchoolFounds { get; set; }
        public Nullable<int> HEGCSubmittedQty { get; set; }
        public string HEGCSubmitteds { get; set; }
        public string MSSubmittedPrograms { get; set; }
        public string CCSubmittedPrograms { get; set; }
        public string HEGSubmittedPrograms { get; set; }
        public string MSESubmittedPrograms { get; set; }
        public string HEGCSubmittedPrograms { get; set; }
        public Nullable<int> MCMchoolFoundQty { get; set; }
        public string MCMSchoolFounds { get; set; }
        public Nullable<int> MCMSubmittedQty { get; set; }
        public string MCMSubmitteds { get; set; }
        public string MCMSubmittedPrograms { get; set; }
        public Nullable<bool> SendToCallCriteria { get; set; }
        public Nullable<int> HEGCNewSchoolFoundsQty { get; set; }
        public string HEGCNewSchoolFounds { get; set; }
        public Nullable<int> HEGCNewSubmittedQty { get; set; }
        public string HEGCNewSubmitteds { get; set; }
        public string HEGCNewSubmittedPrograms { get; set; }
    }
}
