//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class submit_record
    {
        public int id { get; set; }
        public Nullable<int> client_ID { get; set; }
        public string AreaOfInterest { get; set; }
        public string ProgramsOfInterestType { get; set; }
        public string Citizenship { get; set; }
        public string EducationLevel { get; set; }
        public string HighSchoolGradYear { get; set; }
        public string DegreeOfInterest { get; set; }
        public string Age { get; set; }
        public string DegreeStartTimeframe { get; set; }
        public string HighSchoolEnrolled { get; set; }
        public string PreviouslyEnrolled { get; set; }
        public string Zip { get; set; }
        public Nullable<System.DateTime> date_submitted { get; set; }
        public string who_submitted { get; set; }
        public string SchoolSubmitted { get; set; }
        public string SelectedSchool { get; set; }
        public string SchoolType { get; set; }
        public string WorkExperience { get; set; }
        public string CurrentlyEmployed { get; set; }
        public string Military { get; set; }
        public string SubmittedData { get; set; }
        public string Result { get; set; }
        public Nullable<int> mfp_id { get; set; }
        public string Group { get; set; }
        public string SecondaryPhone { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string Affiliation { get; set; }
        public string BestTimeToContact { get; set; }
        public string PrimaryPhone { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Email { get; set; }
        public string SubID { get; set; }
        public string RN { get; set; }
        public string NursingDiploma { get; set; }
        public string TeachingCredential { get; set; }
        public string HasInternet { get; set; }
        public string Advisor { get; set; }
        public string AdvisorEmail { get; set; }
        public string TransferStatus { get; set; }
        public string TransferFailedReason { get; set; }
        public Nullable<bool> Override { get; set; }
        public Nullable<bool> heg_submit { get; set; }
        public Nullable<bool> MSESubmitted { get; set; }
    }
}
