//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CLIENT
    {
        public int client_id { get; set; }
        public string client_name { get; set; }
        public string client_address { get; set; }
        public string client_city { get; set; }
        public string client_state { get; set; }
        public string client_zip { get; set; }
        public string client_phone { get; set; }
        public string client_work_phone { get; set; }
        public string client_email { get; set; }
        public Nullable<System.DateTime> client_added { get; set; }
        public string client_added_by { get; set; }
        public string client_AOI { get; set; }
        public string client_POI { get; set; }
        public string client_citizenship { get; set; }
        public string client_education_level { get; set; }
        public string client_high_school_grad_year { get; set; }
        public string client_degree_of_interest { get; set; }
        public string client_age { get; set; }
        public string client_degree_start_timeframe { get; set; }
        public string client_high_school_enrolled { get; set; }
        public string client_previously_enrolled { get; set; }
        public string client_military { get; set; }
        public string client_gender { get; set; }
        public string client_affiliation { get; set; }
        public string client_best_time_to_contact { get; set; }
        public string client_ip { get; set; }
        public string client_mfp_id { get; set; }
        public string client_sub_id { get; set; }
        public string client_submitted { get; set; }
        public string client_attended_class { get; set; }
        public string client_computer { get; set; }
        public string client_contacted_school { get; set; }
        public string client_rn { get; set; }
        public string client_nursing { get; set; }
        public string client_teaching_cred { get; set; }
        public string client_has_internet { get; set; }
    }
}
