//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dax.Scrapping.Appraisal
{
    using System;
    using System.Collections.Generic;
    
    public partial class vicidial_list
    {
        public long lead_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public byte[] modify_date { get; set; }
        public string status { get; set; }
        public string theuser { get; set; }
        public string vendor_lead_code { get; set; }
        public string source_id { get; set; }
        public Nullable<int> list_id { get; set; }
        public Nullable<decimal> gmt_offset_now { get; set; }
        public string called_since_last_reset { get; set; }
        public string phone_code { get; set; }
        public string phone_number { get; set; }
        public string title { get; set; }
        public string first_name { get; set; }
        public string middle_initial { get; set; }
        public string last_name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string province { get; set; }
        public string postal_code { get; set; }
        public string country_code { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string alt_phone { get; set; }
        public string email { get; set; }
        public string security_phrase { get; set; }
        public string comments { get; set; }
        public Nullable<int> called_count { get; set; }
        public Nullable<System.DateTime> last_local_call_time { get; set; }
        public Nullable<int> rank { get; set; }
        public string owner { get; set; }
        public Nullable<int> entry_list_id { get; set; }
        public string user_program { get; set; }
        public string user_program_choice { get; set; }
    }
}
